import { Inter } from "next/font/google";
import "./globals.css";
import AllProvider from "@/components/provider/AllProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Redux",
  description: "Generated by Abu Taher",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" id="root">
      <body className={inter.className}>
        <AllProvider>{children}</AllProvider>
      </body>
    </html>
  );
}
